# r/Economics

#### In this notebook, 'Economics' subreddit data will be collected.

In [2]:
# code from: https://medium.com/swlh/how-to-scrape-large-amounts-of-reddit-data-using-pushshift-1d33bde9286
#pip install pmaw

In [4]:
import pandas as pd
from pmaw import PushshiftAPI
import datetime as dt

In [3]:
api = PushshiftAPI()

In [4]:
#before the first of December
before = int(dt.datetime(2021,12,1,0,0).timestamp())
#after the first of January
after = int(dt.datetime(2021,1,1,0,0).timestamp())

subreddit = 'Economics'

# Limit the data collection to 10_000 
limit = 10000

In [5]:
submissions = api.search_submissions(subreddit = subreddit, limit = limit, before = before, after = after)

INFO:pmaw.PushshiftAPIBase:Checkpoint:: Success Rate: 50.00% - Requests: 100 - Batches: 10 - Items Remaining: 5002
INFO:pmaw.PushshiftAPIBase:Total:: Success Rate: 68.75% - Requests: 160 - Batches: 16 - Items Remaining: 0

In [6]:
submissions_df = pd.DataFrame(submissions)

In [7]:
submissions_df.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,gallery_data,media_metadata,is_created_from_ads_ui,author_is_blocked,author_cakeday,distinguished,gilded,suggested_sort,crosspost_parent,crosspost_parent_list
0,[],False,benh999,None,[],None,text,t2_2bqswhg2,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,mrkanyebest,None,[],None,text,t2_2707mb4w,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,Bonboniru,None,[],None,text,t2_39m1rwf0,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,gock8383,None,[],None,text,t2_2yf1l81b,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,fizzlepizz77,None,[],None,text,t2_1k65wy1z,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
submissions_df.shape

(10000, 83)

In [9]:
submissions_df.to_csv('../data/economics.csv', index = False)

In [5]:
#Not wanting to pull data again from subreddit...
eco = pd.read_csv('../data/economics.csv')

eco.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,gallery_data,media_metadata,is_created_from_ads_ui,author_is_blocked,author_cakeday,distinguished,gilded,suggested_sort,crosspost_parent,crosspost_parent_list
0,[],False,benh999,NaN,[],NaN,text,t2_2bqswhg2,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,mrkanyebest,NaN,[],NaN,text,t2_2707mb4w,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,Bonboniru,NaN,[],NaN,text,t2_39m1rwf0,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,gock8383,NaN,[],NaN,text,t2_2yf1l81b,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,fizzlepizz77,NaN,[],NaN,text,t2_1k65wy1z,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Create dataframe with only two columns: subreddit name and title of each post
econ = eco[['subreddit', 'title']]

econ.head()

   subreddit                                              title
0  Economics                   Taiwan's exports hit new Q1 high
1  Economics  Blockchain Technology and Google Docs? Theyâ€™re...
2  Economics  How Americaâ€™s Great Economic Challenge Suddenl...
3  Economics  Massive Bitcoin Mining Could Disrupt China's G...
4  Economics                               China will shoot....

In [7]:
econ.to_csv('../data/sub-economics.csv', index = False)